it_project_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path

from tasks.views import (
    index,
    WorkerListView,
    WorkerCreateView,
    WorkerDetailView,
    WorkerPositionUpdateView,
    WorkerDeleteView,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskAssignView,
    NotificationView,
    TaskUrgentHighView,
    TaskCompletedView
)


urlpatterns = [
    path("", index, name="index"),
    path("workers/", WorkerListView.as_view(), name="workers-list"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"
    ),
    path(
        "worker/<int:pk>/update/",
        WorkerPositionUpdateView.as_view(),
        name="worker-update",
    ),
    path(
        "worker/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path("tasks/", TaskListView.as_view(), name="tasks-list"),
    path(
        "tasks/urgnent_high/",
        TaskUrgentHighView.as_view(),
        name="high-priority-tasks-list"
    ),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path("tasks/<int:pk>/assign/",
         TaskAssignView.as_view(),
         name="assign-member"
    ),
    path(
        "notifications/",
        NotificationView.as_view(),
        name="notifications"
    ),
    path(
        "tasks/completed/",
        TaskCompletedView.as_view(),
        name="tasks-completed-list"
    ),
    ]

app_name = "tasks"

tasks/models.py
from django.urls import reverse
from typing import Any
from it_project_task_manager.settings import AUTH_USER_MODEL
from django.contrib.auth.models import AbstractUser
from django.db import models


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        to=Position,
        on_delete=models.RESTRICT,
        related_name="worker_position",
        null=True
    )

    class Meta:
        ordering = ["username", "position"]

    def __str__(self) -> str:
        return (f"username: {self.username} |" +
                f" full_name: {self.first_name} {self.last_name} |" +
                f" position: {self.position}")

    def get_absolute_url(self) -> Any:
        return reverse("tasks:worker-detail", kwargs={"pk": self.pk})


class Task(models.Model):
    class PriorityType(models.TextChoices):
        URGENT = "Urgent", "Urgent"
        HIGH = "High", "High"
        MEDIUM = "Medium", "Medium"
        LOW = "Low", "Low"

    name = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    deadline = models.DateField()
    is_completed = models.BooleanField(verbose_name="task_status", default=False)
    priority = models.CharField(max_length=6, choices=PriorityType.choices)
    task_type = models.ForeignKey(to=TaskType, on_delete=models.PROTECT)
    assignees = models.ManyToManyField(to=AUTH_USER_MODEL)

    def __str__(self):
        return f"{self.name} -  {self.priority} priority, Deadline: {self.deadline} Is_Completed: {self.is_completed}"

    class Meta:
        ordering = ["deadline", "priority"]

tasks/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


from tasks.models import Worker, Task, Position


class DateInput(forms.DateInput):
    input_type = 'date'


def validate_position(position: Position) -> Position:
    if position not in Position.objects.all():
        raise ValidationError(
            "Position must be one of the defined in the Task Manager"
        )

    return position


class WorkerCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "position",
            "first_name",
            "last_name",
        )


class AssigneesForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["assignees"]

    def clean_position(self) -> Position:
        return validate_position(self.cleaned_data["assignees"])


class WorkerPositionUpdateForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = ["position"]

    def clean_position(self) -> Position:
        return validate_position(self.cleaned_data["position"])


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=44,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"})
    )


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=44,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by task name"})
    )

tasks/views.py
from datetime import datetime, timedelta
from typing import Any
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_POST

from .forms import (
    WorkerSearchForm,
    WorkerCreationForm,
    WorkerPositionUpdateForm,
    TaskSearchForm,
    AssigneesForm
)
from .models import Worker, Task


@login_required
def index(request):
    """View function for the home page of the site."""
    worker_list = Worker.objects.select_related("position")
    tasks_list = Task.objects.prefetch_related("assignees")
    logged_worker = request.user
    num_workers = worker_list.count()
    num_tasks = tasks_list.count()
    num_tasks_is_solved = tasks_list.filter(is_completed=True).count()
    urgent_and_high = tasks_list.filter(priority__in=["Urgent", "High"], is_completed=False).count()
    current_user_task_list = tasks_list.filter(assignees__in=[request.user.id])

    context = {
        "num_workers": num_workers,
        "num_tasks": num_tasks,
        "num_tasks_is_solved": num_tasks_is_solved,
        "urgent_and_high": urgent_and_high,
        "worker_list": worker_list,
        "current_user_task_list": current_user_task_list,
        "logged_worker": logged_worker,
    }

    return render(request, "tasks/index.html", context=context)


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> Any:
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(
            initial={"username": username}
        )

        return context

    def get_queryset(self) -> Any:
        queryset = Worker.objects.select_related("position")
        username = self.request.GET.get("username")

        if username:
            return queryset.filter(username__icontains=username)

        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.select_related("position")

    def get_context_data(self, **kwargs) -> Any:
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['is_admin'] = user.is_superuser
        return context


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm


class WorkerPositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerPositionUpdateForm
    success_url = reverse_lazy("tasks:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 8

    def get_context_data(self, *, object_list=None, **kwargs) -> Any:
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        sort_by = self.request.GET.get("sort_by", "")
        context["search_form"] = TaskSearchForm(
            initial={"name": name}
        )
        context["sort_by"] = sort_by

        return context

    def get_queryset(self) -> Any:
        queryset = Task.objects.prefetch_related("assignees")
        name = self.request.GET.get("name")
        sort_by = self.request.GET.get("sort_by")

        if name:
            return queryset.filter(name__icontains=name)

        if sort_by:
            queryset = queryset.order_by(sort_by)

        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    queryset = Task.objects.prefetch_related("assignees")

    def is_complete(self) -> Any:
        task = self.get_object()
        if self.request.method == "POST":
            is_completed = self.request.POST.get("is_completed")
            task.is_completed = is_completed
            task.save()
            return redirect("tasks:task-detail", pk=task.pk)
        return render(self.request, "tasks/task_detail.html", {"task": task})


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    fields = [
        "name",
        "description",
        "deadline",
        "priority",
        "task_type",
        "assignees"
    ]
    queryset = Task.objects.prefetch_related("assignees")
    # form_class = TaskCreationForm
    success_url = reverse_lazy("tasks:tasks-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    # success_url = reverse_lazy("tasks:tasks-list")
    fields = ["is_completed"]

    def get_success_url(self) -> Any:
        return reverse('tasks:task-detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form) -> Any:
        task = form.save(commit=False)
        is_completed = form.cleaned_data.get('is_completed')
        if is_completed is not None:
            task.is_completed = is_completed
            task.save()
            messages.success(self.request, 'Task status updated successfully.')
        return super().form_valid(form)


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:tasks-list")


@method_decorator(require_POST, name='post')
class TaskAssignView(View):
    template_name = "tasks/assign_user.html"

    def get(self, request, pk) -> Any:
        task = get_object_or_404(Task, pk=pk)
        form = AssigneesForm(initial={"assignees": task.assignees.all()})
        return render(request, self.template_name, {"form": form, "task": task})

    def post(self, request, pk) -> Any:
        task = get_object_or_404(Task, pk=pk)
        form = AssigneesForm(request.POST)
        if form.is_valid():
            assignees = form.cleaned_data["assignees"]
            task.assignees.set(assignees)
            task.save()
            return redirect("tasks:task-detail", pk=task.id)
        return render(request, self.template_name, {"form": form, "task": task})


class NotificationView(LoginRequiredMixin, View):
    template_name = "tasks/notifications.html"

    def get(self, request) -> Any:
        user = request.user
        deadline = datetime.now() + timedelta(days=3)
        tasks = Task.objects.prefetch_related(
            "assignees").filter(
            assignees__in=[user],
            deadline__lte=deadline
        ).order_by("deadline")

        context = {
            'tasks': tasks
        }

        return render(request, self.template_name, context)


class TaskUrgentHighView(LoginRequiredMixin, View):
    template_name = "tasks/urgent_high_priority_task_list.html"

    def get(self, request) -> Any:
        tasks_uh = Task.objects.prefetch_related(
            "assignees"
        ).filter(priority__in=["Urgent", "High"], is_completed=False)

        context = {
            "tasks_uh": tasks_uh
        }
        return render(request, self.template_name, context)


class TaskCompletedView(LoginRequiredMixin, View):
    template_name = "tasks/completed_tasks_list.html"

    def get(self, request) -> Any:
        tasks_completed = Task.objects.prefetch_related(
            "assignees"
        ).filter(is_completed=True)
        context = {
            "tasks_completed": tasks_completed
        }
        return render(request, self.template_name, context)

templates/tasks/assign_user.html
{% extends 'base.html' %}

{% block content %}
  <h1>Assign Team Member</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Assign Members</button>
  </form>
{% endblock %}

templates/tasks/completed_tasks_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Completed Tasks</h1>
  <ul>
    {% for task in tasks_completed %}
      <li>
        <a href="{% url 'tasks:task-detail' pk=task.id %}">{{ task.name }}</a>
      </li>
    {% empty %}
      <p class="text-warning">No completed tasks</p>
    {% endfor %}
  </ul>
{% endblock %}

templates/tasks/index.html
{% extends "base.html" %}

{% block title %} Task Dashboard {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-warning card-header-icon">
            <div class="card-icon">
              <i class="material-icons">list</i>
            </div>
            <p class="card-category">Team Tasks</p>
            <h3 class="card-title">{{ num_tasks }}</h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">info</i>
              <a href="{% url 'tasks:tasks-list' %}" class="text-decoration-none">Show Team Tasks List</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="material-icons">beenhere</i>
            </div>
            <p class="card-category">Team Solved Tasks</p>
            <h3 class="card-title">{{num_tasks_is_solved}}</h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">info</i> <a href="{% url 'tasks:tasks-completed-list' %}">Let's have a look</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-danger card-header-icon">
            <div class="card-icon">
              <i class="material-icons">directions_run</i>
            </div>
            <p class="card-category">Urgent&High Priority Tasks</p>
            <h3 class="card-title">{{ urgent_and_high}}</h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">local_offer</i> <a href="{% url 'tasks:high-priority-tasks-list' %}">Let's look inside</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="card">
          <div class="card-header card-header-tabs card-header-primary">
            <div class="nav-tabs-navigation">
              <div class="nav-tabs-wrapper">
                <span class="nav-tabs-title">Tasks Assigned to Me:</span>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="tab-content">
              <div class="tab-pane active" id="profile">
                <table class="table">
                  <tbody>
                  {% if current_user_task_list %}
                    {% for task in current_user_task_list %}
                    <tr>
                      <td><a href="{% url 'tasks:task-detail' pk=task.id %}">{{ task.name }}</a></td>
                      <td>Deadline: {{ task.deadline}}</td>
                      {% if task.priority == "Urgent" %}
                        <td class="text-danger">{{ task.priority}}</td>
                      {% elif task.priority == "High" %}
                        <td class="text-danger">{{ task.priority}}</td>
                      {% elif task.priority == "Medium" %}
                        <td class="text-warning">{{ task.priority}}</td>
                      {% elif task.priority == "Low" %}
                        <td class="text-success">{{ task.priority}}</td>
                      {% endif %}

                      <td class="td-actions text-right">
                        <button type="button" rel="tooltip" title="Task Info" class="btn btn-primary btn-link btn-sm" onclick="location.href='{% url 'tasks:task-detail' pk=task.id %}'">
                          <i class="material-icons">info</i>
                        </button>
                        {% if task.is_completed == True %}
                          <button type="button" rel="tooltip" title="Completed" class="btn btn-success btn-link btn-sm">
                          <i class="material-icons">done_all</i>
                          </button>
                        {% endif %}

                      </td>
                    </tr>
                    {% endfor %}
                  {% else %}
                    <p>I'm free of tasks. All is completed.</p>
                  {% endif %}
                  </tbody>
                </table>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title">Team members</h4>
{#            <p class="card-category">New employees on 15th September, 2016</p>#}
          </div>
          <div class="card-body table-responsive">
            <table class="table table-hover">
              <thead class="text-warning">
                <th>ID</th>
                <th>Username</th>
                <th>Full name</th>
                <th>Position</th>
              </thead>
              <tbody>
              {% for worker in worker_list %}
                <tr>
                  <td>{{ worker.id }}</td>
                  <td><a class="text-black-50" href="{{ worker.get_absolute_url }}">{{ worker.username }} {% if user == worker %} (Me){% endif %}</a></td>
                  <td>{{ worker.first_name }} {{ worker.last_name }}</td>
                  <td>{{ worker.position }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

    });
  </script>

{% endblock javascripts %}

templates/tasks/notifications.html
{% extends 'base.html' %}

{% block content %}
  <h1>Tasks with 3 days Deadlines</h1>
  <ul>
    {% for task in tasks %}
      <li>
        <a href="{% url 'tasks:task-detail' pk=task.id %}">{{ task.name }}</a> - {{ task.deadline }}
      </li>
    {% empty %}
      <p>No tasks with soon deadlines.</p>
    {% endfor %}
  </ul>
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure you need to delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/tasks/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ task.name }}
    {% if request.user.is_superuser or request.user in task.assignees.all %}
      <a href="{% url 'tasks:task-delete' pk=task.id %}" class="btn btn-danger link-to-page">
        Delete
      </a>
    {% endif %}
  </h1>

  <form method="post" action="{% url 'tasks:task-update' pk=task.id %}" class="d-inline">
    {% csrf_token %}
    <input type="hidden" name="is_completed" value="True">
    <button type="submit" class="btn btn-success">Mark as Completed</button>
  </form>

  <form method="post" action="{% url 'tasks:task-update' pk=task.id %}" class="d-inline">
  {% csrf_token %}
  <input type="hidden" name="is_completed" value="False">
  <button type="submit" class="btn btn-warning">Mark as Not Completed</button>
  </form>


  <p><strong>Priority:</strong> {{ task.priority }}</p>
  <p><strong>Deadline:</strong> {{ task.deadline }}</p>
  <p><strong>Description:</strong> {{ task.description }}</p>
  <p>
    <strong>Assignees:</strong> {% for assignee in task.assignees.all %}
      <a href={% url 'tasks:worker-detail' pk=assignee.id %}>{{ assignee.username }}</a>
  {% endfor %}
  </p>
  <p><strong>Is Completed:</strong> {{ task.is_completed }}</p>
  <a href="{% url 'tasks:assign-member' pk=task.id %}" class="btn btn-primary">Assign Team Member</a>
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create a Task</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Create Task</button>
  </form>
{% endblock %}

templates/tasks/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="text-center">
    Tasks list
    {% if request.user.is_staff %}
      <a href="{% url 'tasks:task-create' %}" class="btn btn-primary link-to-page float-">
        Create Task
      </a>
    {% endif %}

  </h1>

  <form action="" method="get" class="form-inline">
    {{search_form|crispy}}
    <input type="submit" value="Find" class="btn btn-secondary">
  </form>

  {% if task_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Task type</th>
        <th>Deadline</th>
        <th>Is completed</th>
        <th>Priority</th>
        <th>Assignees</th>
      </tr>
        {% for task in task_list %}
          <tr>
            <td>
              <a href="{% url 'tasks:task-detail' pk=task.id %}">{{ task.id }}</a>
            </td>
            <td>
              {{ task.name }}
            </td>
            <td>
              {{ task.task_type }}
            </td>
            <td>
                {{ task.deadline }}
            </td>
            <td>
                {{ task.is_completed }}
            </td>
            <td>
                {{ task.priority }}
            </td>
            <td>
                {% for assignee in task.assignees.all %}
                {{ assignee.username }} <br>
                {% endfor %}
            </td>
          </tr>
        {% endfor %}
    </table>
  {% else %}
    <p>There are no tasks for the team.</p>
  {% endif %}
{% endblock %}

templates/tasks/urgent_high_priority_task_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Team Tasks with Urgent&High Priority</h1>
  <ul>
    {% for task in tasks_uh %}
      <li>
        <a href="{% url 'tasks:task-detail' pk=task.id %}">{{ task.name }}</a> - {{ task.deadline }}
      </li>
    {% empty %}
      <p>No tasks with soon deadlines.</p>
    {% endfor %}
  </ul>
{% endblock %}

templates/tasks/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure to delete worker?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/tasks/worker_detail.html
{% extends "base.html" %}

{% block title %} Page User {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">{{ worker.username }} Profile</h4>
                </div>
                <div class="card-body">
                  <form>
                    <div class="row">
                      <div class="col-md-2">
                        <div class="form-group">
                          <label class="bmd-label-floating">UserID</label>
                          <input type="text" class="form-control" disabled value="{{ worker.id }}">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Username</label>
                          <input type="text" class="form-control" value="{{ worker.username }}">
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label class="bmd-label-floating">Email address</label>
                          <input type="email" class="form-control" value="{{ worker.email }}">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label class="bmd-label-floating">Fist Name</label>
                          <input type="text" class="form-control" value="{{ worker.first_name }}">
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label class="bmd-label-floating">Last Name</label>
                          <input type="text" class="form-control" value="{{ worker.last_name }}">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Position</label>
                          <input type="text" class="form-control" disabled value="{{ worker.position }}">
                        </div>
                      </div>
                    </div>
                      {% if request.user.is_superuser %}
                        <a href="/admin/tasks/worker/" class="btn btn-primary pull-right">Update Profile</a>
                        <div class="clearfix"></div>
                    {% else %}
                    {% endif %}

                  </form>
                </div>
              </div>
            </div>
          </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/tasks/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create worker</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/tasks/worker_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1 class="text-center">
      Team Members
      <a href="{% url 'tasks:worker-create' %}" class="btn btn-success link-to-page">
        Add Team Member
      </a>
    </h1>

  <form action="" method="get" class="form-inline">
    {{search_form|crispy}}
    <input type="submit" value="Find" class="btn btn-secondary">

  </form>

    {% if worker_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Position</th>
      </tr>
    {% for worker in worker_list %}
      <tr>
        <td>{{ worker.id }}</td>
        <td><a href="{{ worker.get_absolute_url }}">{{ worker.username }} {% if user == worker %} (Me){% endif %}</a></td>
        <td>{{ worker.first_name }}</td>
        <td>{{ worker.last_name }}</td>
        <td>{{ worker.position }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no workers.</p>
    {% endif %}
{% endblock %}